### ISSUE TITLE
GLOBALS when using spherify

### ISSUE THREAD

**Issue by suptimq** [snap-research/R2L#10]
Hi, I am trying to generate pseudo ground truth while using the spherify setup. It seems like you didn't create the `GLOBALS` variable in this case. I am wondering what would be the right thing to put.
```python
    if spherify:
        poses, render_poses, bds = spherify_poses(poses, bds)

        global GLOBALS
        GLOBALS = {}
        GLOBALS['c2w'] = x
        GLOBALS['up'] = x
        GLOBALS['rads'] = x
        GLOBALS['focal'] = x
        GLOBALS['poses'] = x
```

**Comment by MingSun-Tse** [comment]
Hi @suptimq , thanks for your interest! In the paper we did not use this spherify option, so did not add the code for this case. Right now I don't have the clue either. I may need to check the detailed code again. Meanwhile, could you please provide more background info, like, in what project or paper, you would like to use this spherify option?

**Comment by suptimq** [comment]
Hi, thanks for the quick response! I am working on applying R2L into a 360-degree scene so I have to use the spherify option in training. I did give it a try and wondered what is your thought.

```python
#####################
def spherify_poses(poses, bds):

    [Original Code]
    
    global GLOBALS
    GLOBALS = {}
    GLOBALS['c2w'] = poses_avg(poses_reset)
    GLOBALS['up'] = normalize(poses_reset[:, :3, 1].sum(0))
    GLOBALS['rads'] = 0     # not used in get_rand_pose_v2
    GLOBALS['focal'] = 0      # not used in get_rand_pose_v2
    GLOBALS['poses'] = poses_reset  # @mst: will be used later

    return poses_reset, new_poses, bds
```

**Comment by MingSun-Tse** [comment]
1. As you may notice, we need these GLOBALS because they will be used in the [get_rand_pose function](https://github.com/snap-research/R2L/blob/be28bbce3f434fa059039ad9c902dc7fc151ddc9/dataset/load_llff.py#L187). So how to implement these GLOBALS depends on what information is needed in get_rand_pose when using the spherify option.

2. Meanwhile, if your target is to apply R2L to 360 scenes, one potential solution is to use the [get_rand_pose function](https://github.com/snap-research/R2L/blob/be28bbce3f434fa059039ad9c902dc7fc151ddc9/dataset/load_blender.py#L359) in Blender dataset, which does not need these GLOBALS. The images in the Blender dataset are also from 360 scenes, although they are synthetic, without background, so much simpler. But if you target an unbounded 360 real scenes (like those in [Mip NeRF 360](https://jonbarron.info/mipnerf360/)), this way may not work well (based on my quick intuition).

**Comment by suptimq** [comment]
Hi, thanks for pointing out the function in Blender dataset. I will give it a try! At the same time, could you explain why it is not likely to work for unbounded 360 real scenes based on your intuition?

**Comment by MingSun-Tse** [comment]
It is not "not likely". You may give it a shot. _Possibly_ it can work well. Before we have any experiments, my current intuition is that, unbounded 360 real scenes have a large variety of view directions and typically have many more details than the simple objects in Blender or scenes in LLFF (where the camera views are pretty limited). So simply put, it is the *inherent scene complexity* in unbounded 360 real scenes that makes me "feel" R2L may encounter some problems dealing with these cases. But hard to say definitely; we still need experimental results for confirmation.

**Comment by suptimq** [comment]
I see. Thanks for the explanation! I did see a bunch of pseudo images that are essentially backgrounds using the *GLOBALS* I proposed.
