### ISSUE TITLE
Large gap between training time and test time

### ISSUE THREAD

**Issue by cv-dote** [snap-research/R2L#9]
Thanks for your wonderful work.  

I am trying to reproduce your experiments on my machine.  
I found that there is a large gap between training time and test time.  
When I train the R2L model, it takes over 0.5 [sec/iteration] (the number of rays is 1024), but in test time, it takes only under 1 [sec/image], though one 800×800 image contains 640000 rays.  
Why do these differences occur?

**Comment by MingSun-Tse** [comment]
Hi, thanks for your interest! You might get it wrong because the number of training rays should be: 24 (this is the number of .npy files, --N_rand = 20, and since we use hard example collecting, it would append another 4, making it to 24) * 4096 (#rays per npy file) = **98304 rays per iter**, not 1024 (1024 is the #rays of the original nerf method, not ours). Hope this can answer your question.

**Comment by cv-dote** [comment]
Now I understand the actual number of rays. But even if num_rays is 98304, it is about a tenth of the number of rays contained in a single image. So still there is some gap between them. Does the gap comes from "torch.no_grad()" ?

**Comment by MingSun-Tse** [comment]
I guess so. Training has forward and backward, so at least doubling the time in inference (some other issues like parallelism may also play a small part)

**Comment by cv-dote** [comment]
I get it.  
Thank you for answering my question.   

I'll close this issue.
